### PR TITLE
Analogue trigger display, non-electron version

### PR DESCRIPTION
**Pull request by ephphatha**
Sorry the whitespace changes make the whole file look different. I updated the triggers to show how much travel was being used and did some minor layout changes to line things up a bit more evenly.

### CODE REVIEW

**Comment by Tiyenti** [comment]
Not at home atm so I can't fully look over this, but I'd say using try/catch to avoid errors is probably a better idea than using a separate file for the non-electron version. I did that in my randomiser tracker and was planning to do it here as well, but never got around to it

**Comment by ephphatha** [comment]
I wasn't able to test the electron specific stuff actually runs, but wrapping the window size logic was simple enough and it works fine in a browser/as an OBS BrowserSource.

**Comment by Tiyenti** [comment]
Alright, home now.

I'm not the hugest fan of the analog trigger throw display. Admittedly, I don't think it's necessary. I'm not against having one, per se, but I'd much rather have it be shown by opacity instead of a gauge, since it looks less in your face that way. I guess it would be less useful like that, but with this implementation I'd rather not have them at all.

It really doesn't make sense for the bumpers to be shorter than the triggers, since on the controller itself they are physically the wider buttons, and I don't think it looks all that more aesthetically pleasing, either. The rest of the changes you've made on this front are great, though.

Admittedly, these are pretty petty personal complaints, and probably mostly stem from how much I've played Distance, where the bumpers are front-and-center (heh) and the triggers pretty much completely neglected. Some kind of option system might be ideal, but I'd rather have sane(ish) defaults than crowd it with options, I think less is more for this kind of thing.

Either way, while some of the stuff you've done is great (like implementing the whole "you don't have to run it in electron" thing for me :P), overall I personally prefer the current version on my branch. ¯\\\_(ツ)_/¯

**Comment by ephphatha** [comment]
My main aim with the trigger throw display was to make it more useful for other racing games where throttle/brake control is more important. The bumpers got sized down to be the same width as the space taken up by the d-pad/face buttons both to line them up and give more space for the triggers so the scale was more visible. And I agree that providing options wouldn't help, especially since I think that'd then rule out using OBS browser source.

I'll close this request since I didn't do the sensible thing and base it off a branch/tag (so it picked up a bunch of changes that didn't really need to be merged), but did you want me to make another pull request with just the browser compat and alignment changes (keeping the bumpers at their current width)? I can easily add a display of the trigger inputs by opacity as well if you wanted.

**Comment by Tiyenti** [comment]
Yeah, that'd be good.

Sorry for the late reply, I've been busy playing Celeste :P

**Pull request closed without merging**
